name: build-and-test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Flake
        run: |
          python -m venv ve
          ./ve/bin/pip install flake8

      - name: Run Flake
        run: ./ve/bin/flake8 ctlsettings
